transformer/build.gradle
Fixes https://github.com/eclipse/transformer/issues/6
=> deps: Update to use bnd 5.1.0 release

org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/SignatureRule.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ManifestActionImpl.java, pom.xml
Some javadoc errors had to be fixed to get the javadoc artifact to
build.
=> build: Add javadoc and sources artifacts

.github/scripts/build.sh, .github/workflows/cibuild.yml, pom.xml, settings.xml
GPG sign artifacts in the build.
Eclipse has provisioned the necessary GPG credentials as secrets in the repo. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=563870#c14.
=> GPG sign artifacts

.github/workflows/cibuild.yml, pom.xml
Reverts eclipse/transformer#55
The attempt to use the passphrase in maven failed. Need to get Eclipse to fix the passphrase.
=> Revert "build: Use passphrase in maven"

pom.xml
https: //central.sonatype.org/pages/apache-maven.html#deploying-to-ossrh-with-apache-maven-introduction
=> ci: Replace maven-deploy-plugin with nexus-staging-maven-plugin

org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-renames.properties
Further package rename rules - I'm not sure the current set is complete. This is the set of rules we currently use on TomEE.
=> Adding packages for replacement.

pom.xml
=> build: Remove unused mockito dependency

org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java
Rewrote Transformer.relativize using java.nio.file.Path.  The updated implementation correctly includes the full path of the base reference before finding path of the sibling reference.
Transformer.relativize is used when locating second tier text substitution property files.  The second tier files are supposed to be siblings of their parent first tier text substitution master property file.  The old implementation did not correct include the full path of the first tier file, with the result that incorrect locations were obtained for second tier files.
=> Re-implement Transformer.relative using Path.

org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java
Option details:
```
WIDEN_ARCHIVE_NESTING("w", "widen", "Widen archive nesting",
!OptionSettings.HAS_ARG, !OptionSettings.HAS_ARGS,
!OptionSettings.IS_REQUIRED, OptionSettings.NO_GROUP),
```
Added nestings:
```
if (widenArchiveNesting) {
jarAction.addAction(jarAction);
jarAction.addAction(zipAction);
rarAction.addAction(zipAction);
warAction.addAction(zipAction);
earAction.addAction(zipAction);
zipAction.addAction(zipAction);
}
```
=> Enable jar-in-jar nesting

org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties, org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-xml-dd.properties
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> Add transformations for Jakarta Faces config files.

.github/scripts/build.sh, .github/scripts/publish.sh, .github/workflows/cibuild.yml, pom.xml
=> setup-java action fixed

NOTICE, org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/TransformerLoggerFactory.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/TransformProperties.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/util/FileUtils.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/util/PropertiesUtils.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformManifest.java, pom.xml, transformer-maven-plugin/pom.xml
Some build fixes and an API refactor to remove an impl leakage into the API.
=> Build fixes

org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/LoggerSettings.java, org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/TransformerCLI.java, org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/TransformerLoggerFactory.java, org.eclipse.transformer.cli/src/test/java/transformer/test/TestCommandLine.java, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties, org.eclipse.transformer/src/main/java/org/eclipse/transformer/AppOption.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ByteDataImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/JavaActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ManifestActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/util/ManifestWriter.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformClass.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformManifest.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformXML.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformerMultiText.java, org.eclipse.transformer/src/test/java/transformer/test/TestURL.java, org.eclipse.transformer/src/test/java/transformer/test/TestUtils.java, org.eclipse.transformer/src/test/java/transformer/test/TransformClassLoader.java
Fixes https://github.com/eclipse/transformer/issues/142
Fixes https://github.com/eclipse/transformer/issues/135
Closes #198 
Closes #199
=> Add --trace option and move some logging to trace level to reduce debug output

org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java
Fixes https://github.com/eclipse/transformer/issues/194
=> output: Create parent directory before opening output file

org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/Action.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/DirectoryActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/JavaActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ManifestActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/NullActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/PropertiesActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java
We need to have ByteData apply(ByteData) implementations perform
the start/stop recording.
=> transformer: Refactorings from development work on Bnd Analyzer plugin

org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ByteDataImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/CompositeActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigChangesImpl.java
Also some other minor changes.
=> serviceloader: Fix to not ignore only name change on resourse

org.eclipse.transformer/src/main/java/org/eclipse/transformer/AppOption.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/CompositeAction.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ChangesImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassChangesImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/CompositeActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerChangesImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/DirectoryActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigChangesImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java
Some more refactorings from the work on the Bnd Analyzer plugin.
=> Bnd analyzer fixes

.github/scripts/codeql-build.sh, .github/workflows/cibuild.yml, .github/workflows/codeql-analysis.yml
Add code scanning to the project.
=> ci: Add code scanning

CODE_OF_CONDUCT.md, SECURITY.md, org.eclipse.transformer.parent/pom.xml
Also add missing community files.
=> Deps update

DEV.md, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/ActionType.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/EarActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/RarActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/WarActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ZipActionImpl.java
=> Defend against ZipSlip

org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java
Fixes https://github.com/eclipse/transformer/issues/39
=> xml: Properly configure SAXParserFactory

org.eclipse.transformer.parent/pom.xml
Version 0.3.0-SNAPSHOT has been in use long enough that we need a
new version.
=> build: Raise version to 0.4.0

bnd-plugins/org.eclipse.transformer.bnd.analyzer/src/main/java/org/eclipse/transformer/bnd/analyzer/AnalyzerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/TransformProperties.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/Action.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/ActionType.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/DirectoryActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/JavaActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ManifestActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/RenameActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/SignatureRuleImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ZipActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/util/SignatureUtils.java, org.eclipse.transformer/src/test/java/org/eclipse/transformer/action/impl/RenameActionTest.java, org.eclipse.transformer/src/test/java/org/eclipse/transformer/util/FileUtilsTest.java, org.eclipse.transformer/src/test/java/org/eclipse/transformer/util/SignatureUtilsTest.java, org.eclipse.transformer/src/test/java/transformer/test/CaptureTest.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformClass.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformManifest.java, org.eclipse.transformer/src/test/java/transformer/test/TransformClassLoader.java, org.eclipse.transformer/src/test/resources/transformer/test/manifest-renames.properties
Fixes for package renaming including wildcard support and non-class resources in a renamed package.
=> Rename wildcard fixes

org.eclipse.transformer.parent/pom.xml, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/CompositeActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ContainerActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/RenameActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/SignatureRuleImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java
Change to use the RC1 build of Bnd 6.3.0 now that Bnd is ramping down 6.3 for release.
Also some other minor fixes.
=> Bnd 6.3.0-RC1

org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-application-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-beans-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-ejb-jar-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-faces-config-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-permissions-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-persistence-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-ra-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-web-xml.properties
Fix for https://github.com/eclipse/transformer/issues/323 (Option 2)
Signed-off-by: tsyamamoto <tsyamamoto@fujitsu.com>
=> Fix for the problem "Jakarta EE deployment descriptor schema conversion is insufficient."

org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/ByteData.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ByteDataImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/util/FileUtils.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/util/LineSeparatorBufferedReader.java, org.eclipse.transformer/src/test/java/transformer/test/LineSeparatorBufferedReaderTest.java
* Fixes #292 
Signed-off-by: Ryosuke Okada <ryosuke.okada@fujitsu.com>
=> Fix #292 New line codes in text files are always converted to LF only

CODE_OF_CONDUCT.md, CONTRIBUTING.md, DEV.md, INFRA.md, README.md, RULES.md, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-selection.properties, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/PropertiesActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java, org.eclipse.transformer/src/test/java/transformer/test/TestTransformPropertiesFile.java
Previously, content was not processed.
Fixes https://github.com/eclipse/transformer/issues/290
Also, some minor changes to docs and code.
=> Update PropertiesActionImpl to transform content of files

org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties
https://github.com/eclipse/transformer/issues/341
Signed-off-by: tsyamamoto <tsyamamoto@fujitsu.com>
=> Fix for the problem "Some package names in Deployment Descriptor are not transformed."

org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/ActionType.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ElementActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/JSPActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/JavaActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/PropertiesActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ZipActionImpl.java
Improve resource name matching abstraction. 
Also fix default selection inclusion when using no selection rules with an immediate
selection.
=> Resource name matching

org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-persistence-orm-xml.properties, org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties
Fixes https://github.com/eclipse/transformer/issues/356
=> rules: Add default Jakarta rule for orm.xml

org.eclipse.transformer.parent/pom.xml, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/Changes.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ChangesImpl.java, org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ZipActionImpl.java
=> feat(#462) add timings jar war
