eclipse-transformer/transformer

- transformer/src/main/java/org/eclipse/transformer/action/impl/SignatureRuleImpl.java
Fix for issue: https://github.com/eclipse/transformer/issues/22
Handle '/' in addition to '.'
> 22 - Incorrect sub-package transformation

- transformer/src/main/java/org/eclipse/transformer/Transformer.java
Fixes https://github.com/eclipse/transformer/issues/31
Signed-off-by: JF Denise <jdenise@redhat.com>
Expose changes that could have occurred. We have an immediat use-case for it. If the transformed jar is signed, action must be taken.
> 31 Extend transformer public API to expose the change information

- .github/workflows/cibuild.yml
- pom.xml
For some reason, the passphrase could not be set into the gpg-agent.
So we try to use it in the maven-gpg-plugin.
> build: Use passphrase in maven

- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformClass.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/data/xformme/Sample_OuterClass.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java
There are some cases where a class A encloses another class B, and B makes a reference to A, the reference may not be correctly re-written.
> Fix issue where enclosing class references are not correctly updated

- org.eclipse.transformer.cli/pom.xml
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestLoad.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformServiceConfig.java
- org.eclipse.transformer.cli/src/test/resources/transformer/test/data/complex.properties
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java
- pom.xml
This addresses issue #61. The fix simply ensures that the inputLength is taken into account when reading into a ByteArrayInputStream.
I've included a test with two resources in a jar file, and processing them with a Jar action configured to work on both properties files and service loader files.
Signed-off-by: Jonathan Gallimore <jgallimore@tomitribe.com>
> 61 Fix issue where service loader files can become corrupted

- org.eclipse.transformer.maven/pom.xml
- org.eclipse.transformer.maven/src/main/java/org/eclipse/transformer/maven/TransformMojo.java
- org.eclipse.transformer.maven/src/test/java/org/eclipse/transformer/maven/EchoService.java
- org.eclipse.transformer.maven/src/test/java/org/eclipse/transformer/maven/TransformMojoTest.java
- org.eclipse.transformer.maven/src/test/projects/transform-build-artifact/pom.xml
- pom.xml
We discussed this a bit on the old repository, so here it is, rebased against the new Maven build. See https://github.com/tbitonti/jakartaee-prototype/pull/102.
The Mojo provides a classifier parameter, and any attached artifacts get transformed, and the transformed artifacts are attached with whatever value is specified appended to the artifacts classifier.
For example, in the TomEE build we have the following plugin config:
```
<plugin>
<groupId>org.eclipse.transformer</groupId>
<artifactId>org.eclipse.transformer.mave
<version>0.1.1-SNAPSHOT</version>
<configuration>
<classifier>jakartaee9</classifier>
</configuration>
<executions>
<execution>
<goals>
<goal>run</goal>
</goals>
<phase>package</phase>
</execution>
</executions>
</plugin>
```
And the module has the following attached …
> Add simple Maven Plugin

- .github/scripts/publish.sh
- .github/workflows/cibuild.yml
- settings.xml
This avoids any issue with a settings for ossrh having invalid
credentials on a branch or fork build.
> ci: Only use settings.xml for publishing

- RULES.md
- org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/jakarta/JakartaTransformer.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/CaptureTest.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformClass.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformManifest.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformPropertiesFile.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformServiceConfig.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformXML.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/data/Sample_PerClassConstant.java
- org.eclipse.transformer.maven/src/main/java/org/eclipse/transformer/maven/TransformMojo.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/SignatureRule.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/SignatureRuleImpl.java
- org.eclipse.transformer/src/test/java/org/eclipse/transformer/action/impl/ClassActionTest.java
Constant string transformation (#44) and on fix for Annotation Element value of type String (#43).
A user would define a master index such as:
org/jboss/as/jaxrs/JaxrsAnnotations$Constants.class=jaxrs-annotations.properties
org/apache/jasper/compiler/Generator.class=jsp-compiler.properties
org/jboss/as/weld/CdiAnnotations$Constants.class=cdi-annotations.properties
Each properties file would then contain specific mapping for the class.
Note that the transformation also looks inside complex String to replace parts.
Added unit test.
Signed-off-by: JF Denise <jdenise@redhat.com>
> Fixes for Issues #43 and #44

- org.eclipse.transformer.cli/src/test/data/multi/MANIFEST.MF
- org.eclipse.transformer.cli/src/test/data/multi/tier0.renames.properties
- org.eclipse.transformer.cli/src/test/data/multi/tier0.versions.properties
- org.eclipse.transformer.cli/src/test/data/multi/tier1.renames.properties
- org.eclipse.transformer.cli/src/test/data/multi/tier1.versions.properties
- org.eclipse.transformer.cli/src/test/data/multi/tier2.renames.properties
- org.eclipse.transformer.cli/src/test/data/multi/tier2.versions.properties
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestCommandLine.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformerBase.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformerMultiRenames.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformerMultiText.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ActionImpl.java
Enable rules options to be specified multiple times.
Tested via:
transformer.test.TestTransformerMultiText.testMultiText()
-- Setup three tiers of overlapping master text files.  Verify that the overlapping updates are made with last specified taking precedence.  Verify log output when master property file assignments are overlaid.
transformer.test.TestTransformerMultiRenames.testMultiRenames()
-- Setup three tiers of overlapping package rename and package version rules files.  Verify that the overlapping updates are made with last specified taking precedence.  Verify log output when package rename and package version update values are overlaid.
> 85 multi properties

- org.eclipse.transformer.cli/pom.xml
- org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformClass.java
- org.eclipse.transformer.cli/src/test/java/transformer/test/data/Sample_SecurityAPI_Javax.java
- pom.xml
Signed-off-by: Scott Marlow <smarlow@redhat.com>
I would like to prove that javax.security.auth.message.config.AuthConfigFactory => jakarata.security.auth.message.config.AuthConfigFactory rename works (as is expected).  This will help us ensure that this continues to work in the future (for Jakarta EE 8 => EE 9).
Please let me know of what additional changes are needed for this testing.
> add javax.security.auth.message.config.AuthConfigFactory => jakarata.security.auth.message.config.AuthConfigFactory test

- .github/workflows/cibuild.yml
- org.eclipse.transformer.cli/src/test/java/transformer/test/data/Sample_SecurityAPI_Javax.java
- org.eclipse.transformer/src/test/java/org/eclipse/transformer/action/impl/ClassActionTest.java
- pom.xml
We now remove JDK 14 as it is EOL.
> ci: Update workflow to use released JDK 15

- .github/workflows/cibuild.yml
We just want to build the PRs made by dependabot.
> github actions: Configure to not build the dependabot branches

- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/PropertiesActionImpl.java
Changed the properties action name from "Properties file relocate" to "Properties File Action".
> Rename properties file action

- .github/workflows/cibuild.yml
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=563870#c46
> ci: Disable fail-fast until we can get the private key removal fixed

- .github/workflows/cibuild.yml
This is temporary while we wait for GitHub to merge
https://github.com/actions/setup-java/pull/226
> ci: Use fork of actions/setup-java with subkey fix

- org.eclipse.transformer.maven/src/main/java/org/eclipse/transformer/maven/TransformMojo.java
- org.eclipse.transformer.maven/src/test/java/org/eclipse/transformer/maven/TransformMojoTest.java
Add `attach` parameter to maven plugin to allow disabling addition to
attached artifacts.
Fixes https://github.com/eclipse/transformer/issues/137
Closes #138 (replaces that PR).
> maven: add `attach` parameter

- README.md
- Adds some more meaningful link targets for the build state
- Adds a link to the latest release on Maven Central
- Adds more concrete link for the Snapshot releases
- Enhanced documentation part for running the CLI from the command line
> Enhanced README to have some more

- org.eclipse.transformer.cli/pom.xml
- pom.xml
- transformer-maven-plugin/pom.xml
It is not a runtime dependency of the lib. It is only a test dependency.
For the cli, an slf4j impl is necessary, so we have a runtime scope
dependency for cli. We also add it as a test dependency for the
maven plugin project's tests.
> deps: Fix slf4j-simple dependency

- pom.xml
See if this fixes the plugin section of maven-metadata to contain
the goal prefix.
> build: Revert maven-plugin-plugin version

- pom.xml
This is no longer needed since Maven 3.2.5 and we currently use
3.8.4. We also update the maven-plugins-annotations version.
> maven: Remove unneeded configuration for maven-plugin-plugin

- maven-plugins/pom.xml
- pom.xml
This is necessary to ensure they are not deployed by the
nexus-staging-maven-plugin.
> ci: Reactor poms do not inherit from parent pom

- org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java
We also allow package version change without package rename.
There are use cases where a transformation will want to just change the version of a package and not the name.
> classaction: Handle version replacement in OSGi Version annotation

- org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/LoggerSettings.java
- org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/TransformerLoggerFactory.java
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/AppOption.java
Hopefully this PR is better in terms of checks
> feat(#464) add date time cli option

- .github/workflows/cibuild.yml
- .github/workflows/stale.yml
- CONTRIBUTING.md
- INFRA.md
- NOTICE
- README.md
- bnd-plugins/org.eclipse.transformer.bnd.analyzer/pom.xml
- maven-plugins/transformer-maven-plugin/pom.xml
- org.eclipse.transformer.cli/pom.xml
- org.eclipse.transformer.jakarta/pom.xml
- org.eclipse.transformer.parent/pom.xml
- org.eclipse.transformer/pom.xml
- org.eclipse.transformer/src/main/java/org/eclipse/transformer/AppOption.java
Eclipse moved the transformer repo to a new GitHub organization. See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5325
> Update references to GitHub repo which has been moved

- .github/workflows/cibuild.yml
- README.md
- org.eclipse.transformer.parent/pom.xml
See
https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/#self-service-migration and
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6146
> Update build for migration to Central Portal
